import Twilio from "twilio";
import dotenv from "dotenv";

dotenv.config();

/**
 * WhatsApp Integration via Twilio
 *
 * Uses Twilio's WhatsApp API for medication notifications.
 * Dev mode: Uses sandbox number whatsapp:+14155238886
 * Users must first opt in by texting "join <keyword>" to the sandbox number.
 */

// ─── Typed Payload Interface ────────────────────────────────────────────────

export interface WhatsAppPayload {
  phoneNumber: string; // E.164 format, e.g. "+919876543210"
  patientName: string; // Patient's display name
  scheduleText: string; // Pre-formatted medication schedule text
  warnings: string[]; // Safety warnings array
}

/**
 * Format the WhatsApp message body from the payload
 */
const formatMessage = (payload: WhatsAppPayload): string => {
  let message = `💊 *ScriptStream — Medication Schedule*\n\n`;
  message += `Hello ${payload.patientName}! Here's your daily medication plan:\n\n`;
  message += payload.scheduleText;

  if (payload.warnings.length > 0) {
    message += `\n\n⚠️ *Safety Warnings:*\n`;
    payload.warnings.forEach((w, i) => {
      message += `${i + 1}. ${w}\n`;
    });
  }

  message += `\n_This was generated by ScriptStream AI. Always consult your doctor._`;
  return message;
};

/**
 * Format a schedule object into readable text for WhatsApp
 */
export const formatScheduleForWhatsApp = (
  schedule: any,
  patientName: string,
  warnings: string[] = []
): WhatsAppPayload => {
  const lines: string[] = [];

  if (schedule.morning?.length > 0) {
    lines.push(`🌅 *Morning:* ${schedule.morning.join(", ")}`);
  }
  if (schedule.afternoon?.length > 0) {
    lines.push(`☀️ *Afternoon:* ${schedule.afternoon.join(", ")}`);
  }
  if (schedule.evening?.length > 0) {
    lines.push(`🌆 *Evening:* ${schedule.evening.join(", ")}`);
  }
  if (schedule.night?.length > 0) {
    lines.push(`🌙 *Night:* ${schedule.night.join(", ")}`);
  }
  if (schedule.notes?.length > 0) {
    lines.push(`\n📝 *Notes:*`);
    schedule.notes.forEach((n: string) => lines.push(`  • ${n}`));
  }

  return {
    phoneNumber: "", // Caller sets this
    patientName,
    scheduleText: lines.join("\n"),
    warnings,
  };
};

/**
 * Send a WhatsApp notification via Twilio
 *
 * @param payload - Typed WhatsApp payload
 * @returns { success, messageSid?, error? }
 */
export const sendWhatsAppNotification = async (
  payload: WhatsAppPayload
): Promise<{ success: boolean; messageSid?: string; error?: string }> => {
  const accountSid = process.env.TWILIO_ACCOUNT_SID;
  const authToken = process.env.TWILIO_AUTH_TOKEN;
  const fromNumber = process.env.TWILIO_WHATSAPP_FROM || "whatsapp:+14155238886";

  // Check if Twilio is configured
  if (!accountSid || !authToken) {
    console.warn(
      "[WhatsApp] Twilio not configured (TWILIO_ACCOUNT_SID or TWILIO_AUTH_TOKEN missing). Skipping WhatsApp notification."
    );
    return {
      success: false,
      error: "Twilio credentials not configured",
    };
  }

  try {
    const client = Twilio(accountSid, authToken);
    const messageBody = formatMessage(payload);

    const message = await client.messages.create({
      body: messageBody,
      from: fromNumber,
      to: `whatsapp:${payload.phoneNumber}`,
    });

    console.log(
      `[WhatsApp] ✅ Message sent to ${payload.phoneNumber} (SID: ${message.sid})`
    );

    return {
      success: true,
      messageSid: message.sid,
    };
  } catch (error: any) {
    console.error(
      `[WhatsApp] ❌ Failed to send to ${payload.phoneNumber}:`,
      error.message
    );
    return {
      success: false,
      error: error.message,
    };
  }
};
